services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: revive-consecrations:local
    restart: unless-stopped
    container_name: revive-consecrations
    # Environment variables required in Override file
    depends_on:
      - db
    environment:
      DB:
      USER:
      PASS:
  db:
    image: postgres:alpine
    container_name: revive-consecrations-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matthew -d reviveconsecrations"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - revive-network
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
volumes:
  db-data:
networks:
  revive-network:
  proxy: