import { Litany } from "@app/revive-consecrations.types"

export const our_lord: Litany = {
  title: "Litany of the Most Holy Name of Jesus",
  items: [
    "God, the Son, Redeemer of the world",
    "Holy Trinity, One God",
    "Jesus, Son of the Living God",
    "Jesus, Splendor of the Father",
    "Jesus, Brightness of Eternal Light",
    "Jesus, King of Glory",
    "Jesus, Sun of Justice",
    "Jesus, Son of the Virgin Mary",
    "Jesus, Most Amiable",
    "Jesus, Most Admirable",
    "Jesus, Mighty God",
    "Jesus, Father of the World to Come",
    "Jesus, Angel of Great Counsel",
    "Jesus, Most Powerful",
    "Jesus, Most Patient",
    "Jesus, Most Obedient",
    "Jesus, Meek and Humble of Heart",
    "Jesus, Lover of Chastity",
    "Jesus, Lover of Us",
    "Jesus, God of Peace",
    "Jesus, Author of Life",
    "Jesus, Model of Virtues",
    "Jesus, Zealous for Souls",
    "Jesus, Our God",
    "Jesus, Our Refuge",
    "Jesus, Father of the Poor",
    "Jesus, Treasure of the Faithful",
    "Jesus, Good Shepherd",
    "Jesus, True Light",
    "Jesus, Eternal Wisdom",
    "Jesus, Infinite Goodness",
    "Jesus, Our Way and Our Life",
    "Jesus, Joy of Angels",
    "Jesus, King of Patriarchs",
    "Jesus, Master of Apostles",
    "Jesus, Teacher of Evangelists",
    "Jesus, Strength of Martyrs",
    "Jesus, Light of Confessors",
    "Jesus, Purity of Virgins",
    "Jesus, Crown of All Saints",
    "Be merciful, spare us, O Jesus",
    "Be merciful, graciously hear us, O Jesus",
    "From all evil, deliver us, O Jesus",
    "From all sin, deliver us, O Jesus",
    "From Your wrath, deliver us, O Jesus",
    "From the snares of the devil, deliver us, O Jesus",
    "From the spirit of fornication, deliver us, O Jesus",
    "From everlasting death, deliver us, O Jesus",
    "From the neglect of Your inspirations, deliver us, O Jesus",
    "Through the mystery of Your holy Incarnation, deliver us, O Jesus",
    "Through Your Nativity, deliver us, O Jesus",
    "Through Your Infancy, deliver us, O Jesus",
    "Through Your Most Divine Life, deliver us, O Jesus",
    "Through Your Labors, deliver us, O Jesus",
    "Through Your Agony and Passion, deliver us, O Jesus",
    "Through Your Cross and Dereliction, deliver us, O Jesus",
    "Through Your Sufferings, deliver us, O Jesus",
    "Through Your Death and Burial, deliver us, O Jesus",
    "Through Your Resurrection, deliver us, O Jesus",
    "Through Your Ascension, deliver us, O Jesus",
    "Through Your Institution of the Most Holy Eucharist, deliver us, O Jesus",
    "Through Your Joys, deliver us, O Jesus",
    "Through Your Glory, deliver us, O Jesus",
    "Lamb of God, who takes away the sins of the world, spare us, O Jesus",
    "Lamb of God, who takes away the sins of the world, graciously hear us, O Jesus",
    "Lamb of God, who takes away the sins of the world, have mercy on us, O Jesus",
    "Jesus, hear us",
    "Jesus, graciously hear us"
  ]
}

export const our_lady: Litany = {
  title: "Litany of the Blessed Virgin Mary",
  items: [
    "Holy Mother of God",
    "Holy Virgin of Virgins",
    "Mother of Christ",
    "Mother of the Church",
    "Mother of Mercy",
    "Mother of Divine Grace",
    "Mother of Hope",
    "Mother Most Pure",
    "Mother Most Chaste",
    "Mother Inviolate",
    "Mother Undefiled",
    "Mother Most Amiable",
    "Mother Most Admirable",
    "Mother of Good Counsel",
    "Mother of our Creator",
    "Mother of our Savior",
    "Virgin Most Prudent",
    "Virgin Most Venerable",
    "Virgin Most Renowned",
    "Virgin Most Powerful",
    "Virgin Most Merciful",
    "Virgin Most Faithful",
    "Mirror of Justice",
    "Seat of Wisdom",
    "Cause of our Joy",
    "Spiritual Vessel",
    "Vessel of Honor",
    "Singular Vessel of Devotion",
    "Mystical Rose",
    "Tower of David",
    "Tower of Ivory",
    "House of Gold",
    "Ark of the Covenant",
    "Gate of Heaven",
    "Morning Star",
    "Health of the Sick",
    "Refuge of Sinners",
    "Comfort of Migrants",
    "Comforter of the Afflicted",
    "Help of Christians",
    "Queen of Angels",
    "Queen of Patriarchs",
    "Queen of Prophets",
    "Queen of Apostles",
    "Queen of Martyrs",
    "Queen of Confessors",
    "Queen of Virgins",
    "Queen of All Saints",
    "Queen Conceived without Original Sin",
    "Queen Assumed into Heaven",
    "Queen of the Most Holy Rosary",
    "Queen of Families",
    "Queen of Peace",
    "Pray for Us"
  ]
}

export const martyrs: Litany = {
  title: "Litany of the Martyrs",
  items: [
    "St. Stephen",
    "St. Lawrence",
    "St. Vincent",
    "Sts. Fabian and Sebastian",
    "Sts. John and Paul",
    "Sts. Cosmas and Damian",
    "Sts. Gervase and Protase",
    "St. Agnes",
    "St. Cecilia",
    "St. Anastasia",
    "St. Perpetua",
    "St. Felicity",
    "St. Agatha",
    "St. Lucy",
    "St. Agnes",
    "St. Gregory VII",
    "St. Thomas Becket",
    "St. Peter Martyr",
    "St. John Fisher",
    "St. Thomas More",
    "St. John Houghton",
    "St. Edmund Campion",
    "St. Margaret Clitherow",
    "St. Philip Howard",
    "St. John Southworth",
    "St. Oliver Plunkett",
    "St. Maximilian Kolbe",
    "St. Edith Stein",
    "St. Oscar Romero",
    "St. Charles Lwanga",
    "St. Andrew Dung-Lac",
    "St. Paul Miki",
    "St. Pedro Calungsod",
    "St. Lorenzo Ruiz",
    "St. Kateri Tekakwitha",
    "St. Isaac Jogues",
    "St. Jean de Brébeuf",
    "St. René Goupil",
    "St. Charles Garnier",
    "St. Gabriel Lalemant",
    "St. Noël Chabanel",
    "St. Anthony Daniel",
    "St. John de Lalande",
    "St. Roque González",
    "St. Juan del Castillo",
    "St. Alphonsus Rodríguez",
    "St. Miguel Pro",
    "St. José Sánchez del Río",
    "St. Cristóbal Magallanes",
    "St. Mateo Correa Magallanes",
    "St. Rodrigo Aguilar Alemán",
    "St. Luis Batiz Sainz",
    "St. Pedro de Jesús Maldonado",
    "St. Toribio Romo González",
    "St. David Galván Bermúdez",
    "St. Jenaro Sánchez Delgadillo",
    "St. Tranquilino Ubiarco",
    "St. Margarito Flores García",
    "St. Atilano Cruz Alvarado",
    "St. Julio Álvarez Mendoza",
    "St. David Uribe Velasco",
    "St. Manuel Morales",
    "St. Salvador Lara Puente",
    "St. José María Robles Hurtado",
    "St. Sabás Reyes Salazar",
    "St. Mateo Correa Magallanes",
    "St. Justino Orona Madrigal",
    "St. David Roldán Lara",
    "St. Toribio Romo González",
    "St. Jenaro Sánchez Delgadillo",
    "St. Tranquilino Ubiarco",
    "St. Margarito Flores García",
    "St. Atilano Cruz Alvarado",
    "St. Julio Álvarez Mendoza",
    "St. David Uribe Velasco",
    "St. Manuel Morales",
    "St. Salvador Lara Puente",
    "St. José María Robles Hurtado",
    "St. Sabás Reyes Salazar",
    "Pray for Us"
  ]
}

export const angels: Litany = {
  title: "Litany of the Angels",
  items: [
    "St. Michael the Archangel",
    "St. Gabriel the Archangel",
    "St. Raphael the Archangel",
    "All ye holy angels",
    "All ye holy orders of blessed spirits",
    "All ye holy orders of blessed angels",
    "All ye holy orders of blessed archangels",
    "All ye holy orders of blessed principalities",
    "All ye holy orders of blessed powers",
    "All ye holy orders of blessed virtues",
    "All ye holy orders of blessed dominions",
    "All ye holy orders of blessed thrones",
    "All ye holy orders of blessed cherubim",
    "All ye holy orders of blessed seraphim",
    "Guard and protect us",
    "Intercede for us"
  ]
}