services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.node
    image: revive-consecrations:local
    restart: unless-stopped
    container_name: revive-consecrations
    depends_on:
      - db
    networks:
      - proxy
      - revive-network
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
  db:
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    container_name: revive-consecrations-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - revive-network
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
volumes:
  db-data:
networks:
  revive-network:
    name: revive-network
  proxy:
    external: true
    name: proxy